### ISSUE TITLE
您好，有个地方请教您一下。

### ISSUE THREAD

**Issue by gzqstudyios** [WZF-Fei/ZFShoppingCart#1]
-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath在定义cell的方法里面，这句调用为什么写死了，后面的参数为0，0，[self storeOrders:dict isAdded:animated withSectionIndex:0 withRowIndex:0];谢谢您的资源共享。

**Comment by WZF-Fei** [comment]
这句代码是在商品列表中添加商品后block内执行，目的是如果购物清单中有多个section，添加到商品中会默认进入到第一个section。
